<?php
include("../classes/PacienteClass.php");

$paciente = new Paciente($_POST["id"]);
$paciente->apellidos = $_POST["apellidos"];
$paciente->nombre = $_POST["nombre"];
$paciente->num_historia = $_POST["numero_historia"];
$paciente->fecha = $_POST["fecha"];
$paciente->tipo_enferma = $_POST["tipo_enferma"];
$paciente->edad = $_POST["edad"];
$paciente->estado_civil = $_POST["estado_civil"];
$paciente->ocupacion = $_POST["ocupacion"];
$paciente->direccion = $_POST["direccion"];
$paciente->ciudad = $_POST["ciudad"];
$paciente->ciudad = $_POST["ciudad"];
$paciente->telefono = $_POST["telefono"];
$paciente->nif = $_POST["nif"];
$paciente->rh = $_POST["rh"];
$paciente->antecedentes_familiares = $_POST["antecedentes_familiares"];
$paciente->antecedentes_personales = $_POST["antecedentes_personales"];
$paciente->historia = $_POST["historia_clinica"];
$paciente->menarquia = $_POST["menarquia"];
$paciente->tm = $_POST["tm"];
$paciente->fur = $_POST["fur"];
$paciente->edad_sexual = $_POST["edad_sexual"];
$paciente->cantidad = $_POST["cantidad"];
$paciente->dolor = $_POST["dolor"];
$paciente->dispareunia = $_POST["dispareunia"];
$paciente->coitorragias = $_POST["coitorragias"];
$paciente->anticonceptivos = $_POST["anticonceptivos"];
$paciente->ano1 = $_POST["ano1"];
$paciente->ano2 = $_POST["ano2"];
$paciente->ano3 = $_POST["ano3"];
$paciente->ano4 = $_POST["ano4"];
$paciente->ano5 = $_POST["ano5"];
$paciente->ano6 = $_POST["ano6"];
$paciente->embarazo1 = $_POST["embarazo1"];
$paciente->embarazo2 = $_POST["embarazo2"];
$paciente->embarazo3 = $_POST["embarazo3"];
$paciente->embarazo4 = $_POST["embarazo4"];
$paciente->embarazo5 = $_POST["embarazo5"];
$paciente->embarazo6 = $_POST["embarazo6"];
$paciente->parto1 = $_POST["parto1"];
$paciente->parto2 = $_POST["parto2"];
$paciente->parto3 = $_POST["parto3"];
$paciente->parto4 = $_POST["parto4"];
$paciente->parto5 = $_POST["parto5"];
$paciente->parto6 = $_POST["parto6"];
$paciente->peso1 = $_POST["peso1"];
$paciente->peso2 = $_POST["peso2"];
$paciente->peso3 = $_POST["peso3"];
$paciente->peso4 = $_POST["peso4"];
$paciente->peso5 = $_POST["peso5"];
$paciente->peso6 = $_POST["peso6"];
$paciente->sexo1 = $_POST["sexo1"];
$paciente->sexo2 = $_POST["sexo2"];
$paciente->sexo3 = $_POST["sexo3"];
$paciente->sexo4 = $_POST["sexo4"];
$paciente->sexo5 = $_POST["sexo5"];
$paciente->sexo6 = $_POST["sexo6"];


$ret = array();
$ret["success"] = $paciente->guardar();
echo json_encode($ret);